# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:31
from __future__ import unicode_literals

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=Main.models.upload_location)),
                ('video', models.FileField(blank=True, null=True, upload_to='upload_location')),
                ('description', models.TextField()),
                ('size_of_land', models.CharField(max_length=500)),
                ('location_details', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('features', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_name', models.CharField(max_length=100)),
                ('members_role', models.CharField(max_length=100)),
                ('slug_name', models.SlugField(unique=True)),
                ('members_details', models.TextField()),
                ('members_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('members_email', models.EmailField(max_length=254)),
                ('members_image', models.ImageField(blank=True, null=True, upload_to=Main.models.upload_location)),
            ],
        ),
    ]
