# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:52
from __future__ import unicode_literals

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=Main.models.upload_location)),
                ('image_2', models.ImageField(upload_to=Main.models.upload_location)),
                ('image_3', models.ImageField(upload_to=Main.models.upload_location)),
                ('image_4', models.ImageField(upload_to=Main.models.upload_location)),
                ('image_5', models.ImageField(upload_to=Main.models.upload_location)),
                ('description', models.TextField()),
                ('size_of_land', models.IntegerField()),
                ('location_details', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('features', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Team_Meamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_name', models.CharField(max_length=100)),
                ('members_role', models.CharField(max_length=100)),
                ('slug_name', models.SlugField(unique=True)),
                ('members_details', models.TextField()),
                ('members_phone_number', models.IntegerField(blank=True, null=True)),
                ('members_email', models.EmailField(max_length=254)),
                ('members_image', models.ImageField(upload_to=Main.models.upload_location)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
