# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:36
from __future__ import unicode_literals

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=Main.models.upload_location),
        ),
    ]
