# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:23
from __future__ import unicode_literals

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0006_auto_20171008_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_to_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('property_name', models.CharField(max_length=120)),
                ('property_image', models.ImageField(upload_to=Main.models.upload_location)),
                ('property_image_2', models.ImageField(upload_to=Main.models.upload_location)),
                ('description', models.TextField()),
                ('size_of_land', models.IntegerField()),
                ('location_details', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
